
package com.hik.consul.hikconsul.rxjava;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "WebServiceInterface")
public interface WebServiceInterface {
    /**
     *
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    public String say(@WebParam(name = "name")
        String name);

}
