server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8088/eureka/
spring:
  application:
    name: liferibbon
