
server:
  port: 8088
eureka:
  instance:
    hostname: localhost
  server:
#    关闭自我保护
    enable-self-preservation: false
#    服务失效的扫描时间间隔
    eviction-interval-timer-in-ms: 50009
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 是否优先从文件系统加载template，默认值为true 解决包404错误
spring:
  freemarker:
      prefer-file-system-access: false
